### ISSUE TITLE
Add methods to automatically generate ceiling plenums when translating to_honeybee

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/dragonfly-core#20]
Right now, each Dragonfly Room2D results in only one Honeybee Room but there's often a big gap between the ceiling of a Room2D and the floor above. For these cases, we should have the option to generate a ceiling plenum zone when translating the Dragonfly Room2D to_honeybee.  The code to do this should be pretty simple to implement and can follow a similar methodology to what we currently use to split out adiabatic Faces for mismatched ceiling heights within a Story.

**Comment by saeranv** [comment]
@chriswmackey 

Does this method need to account for two vertically adjacent plenum zones in cases where you have both a ceiling plenum and floor plenum stacked on top of eachother? And if so, is the height of each plenum just the (floor_of_level_1 - ceiling_of_level_2) / 2?

Traditionally, I haven't done this in my own modeling, but you mentioned there were cases where there be both a floor and ceiling supply/return system, where this may be required.

**Comment by saeranv** [comment]
@chriswmackey 

One more question: what methods can I use to identify the floor face/floor height of a Room above another Room? 
 
I have a feeling it's somewhere in the Story and Building classes, but I can't seem to find it. All the adjacency checking I can find (in Room2D, and Story) looks only like it's solving adjacency for rooms on the same level.

**Comment by chriswmackey** [comment]
@saeranv ,
Sorry for the late response and for not being clearer in the original issue. I should have clarified that one of the limitations of dragonfly at this point is that it doesn't use Surface boundary conditions between the ceiling of one story and the floor of the next. So the only boundary conditions used for the ceilings of dragonfly Rooms are Adiabatic or Outdoors. Similarly, the only boundary conditions used for the floor of dragonfly Rooms are Adiabatic or Ground.  The [`is_ground_contact` and `is_top_exposed` properties of the Room2D](https://github.com/ladybug-tools/dragonfly-core/blob/master/dragonfly/room2d.py#L411-L429) effectively determine which of the two cases appears in the exported Honeybee model.  So I think you should also use this property to set the boundary condition of your plenums.

And, just to give a quick explanation: I realize that this adiabatic limitation is too great  for some cases and, for those situations, I recommend people use the honeybee instead of dragonfly (or convert the dragonfly model to honeybee and do further edits there). But, for situations where there aren't big temperature differences from one floor to another, the Adiabatic assumption grants a lot of opportunities. For example, we could export each story as a separate EnergyPlus model and parallelize the energy simulation of large buildings much more easily. You can also easily remove/replace a story of a building without having the other stories broken. So that is whay I originally set it up this way.

**Comment by saeranv** [comment]
@chriswmackey 

Thanks for the explanation, and pointing out those ground_contact and top_exposed properties, that'll make everything really simple. I agree that the simplifying assumption of the adiabatic surfaces makes sense for DF purposes. It's definitely a reasonable trade-off that will save a lot of time in model building (no horizontal surface splitting/matching), and simulation time.
