### ISSUE TITLE
Dragonfly improvement request

### ISSUE THREAD

**Issue by frank984** [ladybug-tools/dragonfly-core#68]
Please, in improving the Dragonfly, consider this aspect:
https://discourse.ladybug.tools/t/opening-detailed-file-in-dragonfly/7205/4?u=francesco661

**Comment by mostaphaRoudsari** [comment]
@frank984, discourse is currently down so I can't see the details. In any case, I suggest that you add more details here about your wish.

**Comment by frank984** [comment]
Hi @mostaphaRoudsari!
Here below my comment on discourse:
After a long exchange of messages with @SaeranVasanthakumar , I think it would be useful to add a component that allows modifying the building’s cooling set point and the envelope construction properties…
Considering the dragonfly as it is now, it is not possible to conduct a sensitivity analysis such as, for example, the one conducted in [this study](https://iopscience.iop.org/article/10.1088/1757-899X/245/8/082055/pdf) from which I extracted the following table (the values that the dragonfly allows you to modify are highlighted in yellow):
![5c73b5512be24e74fe8575a5758f0fb3934f0250](https://user-images.githubusercontent.com/6491927/79900729-f8fd9b80-840e-11ea-9c62-3d0a09e40199.png)

From the above-linked paper, the cooling setpoint seems to be relevant in terms of the average UHI effect.
It could be useful to modify also the characteristics of the envelope layers (thickness, conductivity and volumetric heat capacity).
Regards,
F.

**Comment by frank984** [comment]
Considering the structure of the DF Edit Typology Envelope component and that of the DOE ref building LocationSummary.csv, it could be useful to add these options (the most relevant in yellow):
![image](https://user-images.githubusercontent.com/6491927/79943873-65f24f00-846a-11ea-9afc-27e11437ed21.png)

**Comment by chriswmackey** [comment]
I'm going to close out this issue now that we are not addressing it here.
