### ISSUE TITLE
Set Up Environment Variables on Travis

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/dragonfly-core#8]
@mostaphaRoudsari ,

I just need you to put in the GH_TOKEN and PYPI_PASSWORD here:
https://travis-ci.org/ladybug-tools/dragonfly-core/settings

Then you can restart the deployment job here:
https://travis-ci.org/ladybug-tools/dragonfly-core/jobs/602622614

**Comment by mostaphaRoudsari** [comment]
It should be all set.
